### ISSUE TITLE
conda cmake

### ISSUE THREAD

**Issue by matt-chan** [theochem/cellcutoff#13]
Not sure if it's really worth it here (maybe for consistency's sake) but we need the cmake from conda if we want to be able `find_library` to work with conda packages. 

I'm not sure if there's simply a way to add the conda paths to the existing cmake and gcc instead of having to use the versions packaged in Conda? 

(on the other hand, it'll give us some build/run consistency...)

**Comment by tovrstra** [comment]
This is fixed. Roberto does it by default.
