### ISSUE TITLE
OSX builds don't have gcov

### ISSUE THREAD

**Issue by matt-chan** [theochem/cellcutoff#21]
Since the OSX builds are using clang now, gcov doesn't work anymore and can't be linked in (the library doesn't even exist on OSX).

We'll have to switch to llvm-cov if we want to have the same functionality. That is done with the compile flag --coverage. The cmake scripts should be updated to reflect this.

**Comment by matt-chan** [comment]
Temporarily fixing it by removing gcov. We'll have to add it back in once we fix #22

**Comment by matt-chan** [comment]
temporary fix in #23

**Comment by tovrstra** [comment]
This is the doc for clang: https://clang.llvm.org/docs/SourceBasedCodeCoverage.html

We should add compiler flags `-fprofile-instr-generate -fcoverage-mapping` for a DEBUG build with the clang compiler. clang can produce gcov-compatible outputs, which means we have to pass an alternative gcov binary to the gcovr program in Roberto.

**Comment by tovrstra** [comment]
This is superseded by an issue in Roberto: https://github.com/theochem/roberto/issues/7
